[tool.poetry]
name = "elevator-kata"
version = "0.1.0"
description = ""
authors = ["Jelle <jelle@victoor.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
